### ISSUE TITLE
Need for removal BeautifulSoup from CsgoDB source project

### ISSUE THREAD

**Issue by classifiedfear** [classifiedfear/tg_bot_float#11]
There is a way in which i can extract weapon names and skin names right from the page by reading it line by line and matching it against one of the two regexes:
<h3 class="item-box-header.+">(?<item>[\w\s-]+)<\/h3> to extract a weapon name,
<span class='block txt-med txt-white'>(?<item>[\w\s'-]+)<\/span> to extract a skin name.
The (?...) regex group will capture the name for me - i need only to get the value of that group and add it to the list of names.
It will also benefit in terms of performance.

Put these regex expressions into the environment variables from which CsgoDbSourceSettings reads its values. Make sure to properly escape the regexes and then check the values of the environment variables inside the container.

**Comment by aannenko** [comment]
Just for the sake of correctness, here are the two regexes:
`<h3 class="item-box-header.+">(?<item>[\w\s-]+)<\/h3>` - this one is for weapons
`<span class='block txt-med txt-white'>(?<item>[\w\s'-]+)<\/span>` - this one is for skins

**Comment by aannenko** [comment]
Please link your work. If you create and then merge a PR that resolves a certain issue, please either mention this issue in the PR or vice versa. Also issues are supposed to be closed after the PRs are merged.

**Comment by classifiedfear** [comment]
#12 Here is the performed action and merged code.
